<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net472</TargetFramework><LangVersion>latest</LangVersion><Nullable>enable</Nullable></PropertyGroup>
  <ItemGroup>
    <Compile Include="../src/AutoCADPlugin/*.cs" Link="%(Filename)%(Extension)" />
    <Content Include="../assets/Fonts/*.shx" Link="Fonts/%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="../assets/ReferenceStyle.dwg" Link="ReferenceStyle.dwg" CopyToOutputDirectory="PreserveNewest" />
    <Reference Include="AcMgd"><HintPath>D:/Program Files/Autodesk/AutoCAD 2020/acmgd.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="AcDbMgd"><HintPath>D:/Program Files/Autodesk/AutoCAD 2020/acdbmgd.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="AcCoreMgd"><HintPath>D:/Program Files/Autodesk/AutoCAD 2020/accoremgd.dll</HintPath><Private>false</Private></Reference>
  </ItemGroup>
</Project>
